version: 1.12.2
project_url_root: https://www.curseforge.com/minecraft/mc-mods
forge_storage_url_root: https://media.forgecdn.net/files
origin_mod_dir: F:\Game\MultiMC\instances\BWEA\.minecraft\mods
mod_list: mod_list.txt
project_list: project_list.txt
file_list: file_list.txt
user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0
max_thread_job: 5
